destinations = [
    "Lucban, Quezon",
    "Lucena City, Quezon",
    "Sta. Rosa, Laguna",
    "Calamba, Laguna",
    "Los Baños, Laguna",
    "Binangonan, Rizal",
    "Antipolo, Rizal",
    "Angono, Rizal",
    "Taytay, Rizal",
    "Cainta, Rizal",
    "Marikina City, Metro Manila",
    "San Juan City, Metro Manila",
    "Mandaluyong City, Metro Manila",
    "Pasig City, Metro Manila",
    "Quezon City, Metro Manila",
    "Caloocan City, Metro Manila",
    "Valenzuela City, Metro Manila",
    "Malabon City, Metro Manila",
    "Navotas City, Metro Manila",
    "Manila City, Metro Manila",
    "Makati City, Metro Manila",
    "Taguig City, Metro Manila",
    "Pasay City, Metro Manila",
    "Parañaque City, Metro Manila",
    "Las Piñas City, Metro Manila",
    "Muntinlupa City, Metro Manila",
    "Pateros, Metro Manila",
    "San Pedro, Laguna",
    "Biñan, Laguna",
    "Cabuyao, Laguna",
    "San Pablo City, Laguna",
    "Calauan, Laguna",
    "Santa Cruz, Laguna",
    "Victoria, Laguna",
    "Lumban, Laguna",
    "Pila, Laguna",
    "Bay, Laguna",
    "Los Baños, Laguna",
    "Paete, Laguna",
    "Pagsanjan, Laguna",
    "Magdalena, Laguna",
    "Mabitac, Laguna",
    "Siniloan, Laguna",
    "Famy, Laguna",
    "Luisiana, Laguna",
    "Pakil, Laguna",
    "Nagcarlan, Laguna",
    "Rizal, Laguna",
    "Santa Maria, Laguna",
    "Liliw, Laguna",
    "Pila, Laguna",
    "Sta. Cruz, Laguna",
    "Calamba, Laguna",
    "Bay, Laguna",
    "Los Baños, Laguna",
    "Cabuyao, Laguna",
    "Biñan, Laguna",
    "San Pedro, Laguna",
    "Carmona, Cavite",
    "Cavite City, Cavite",
    "Tagaytay City, Cavite",
    "Dasmariñas City, Cavite",
    "Trece Martires City, Cavite",
    "Imus City, Cavite",
    "Bacoor City, Cavite",
    "General Trias City, Cavite",
    "Noveleta, Cavite",
    "Kawit, Cavite",
    "Rosario, Cavite",
    "Tanza, Cavite",
    "Naic, Cavite",
    "Amadeo, Cavite",
    "Gen. Mariano Alvarez, Cavite",
    "Indang, Cavite",
    "Silang, Cavite",
    "Maragondon, Cavite",
    "Ternate, Cavite",
    "Alfonso, Cavite",
    "Magallanes, Cavite",
    "Cuenca, Batangas",
    "San Juan, Batangas",
    "Balayan, Batangas",
    "Tuy, Batangas",
    "Nasugbu, Batangas",
    "Calatagan, Batangas",
    "Lian, Batangas",
    "Laurel, Batangas",
    "Talisay, Batangas",
    "San Jose, Batangas",
    "Lipa City, Batangas",
    "Tanauan City, Batangas",
    "Sto. Tomas City, Batangas",
    "Malvar, Batangas",
    "Ibaan, Batangas",
    "Batangas City, Batangas",
    "Lobo, Batangas",
    "Tingloy, Batangas",
    "San Pascual, Batangas",
    "Bauan, Batangas",
    "Mabini, Batangas",
    "Padre Garcia, Batangas",
    "San Luis, Batangas",
    "Agoncillo, Batangas",
    "San Nicolas, Batangas",
    "Cuenca, Batangas",
    "Taal, Batangas",
    "Santa Teresita, Batangas",
    "Rosario, Batangas",
    "Balete, Batangas",
    "Sto. Tomas, Batangas",
    "Calamba, Laguna",
    "Bay, Laguna",
    "Los Baños, Laguna",
    "Cabuyao, Laguna",
    "Biñan, Laguna",
    "San Pedro, Laguna",
    "Carmona, Cavite",
    "Cavite City, Cavite",
    "Tagaytay City, Cavite",
    "Dasmariñas City, Cavite",
    "Trece Martires City, Cavite",
    "Imus City, Cavite",
    "Bacoor City, Cavite",
    "General Trias City, Cavite",
    "Noveleta, Cavite",
    "Kawit, Cavite",
    "Rosario, Cavite",
    "Tanza, Cavite",
    "Naic, Cavite",
    "Amadeo, Cavite",
    "Gen. Mariano Alvarez, Cavite",
    "Indang, Cavite",
    "Silang, Cavite",
    "Maragondon, Cavite",
    "Ternate, Cavite",
    "Alfonso, Cavite",
    "Magallanes, Cavite",
    "Lemery, Batangas",
    "Calaca, Batangas",
    "Balayan, Batangas",
    "Tuy, Batangas",
    "Nasugbu, Batangas",
    "Calatagan, Batangas",
    "Lian, Batangas",
    "Laurel, Batangas",
    "Talisay, Batangas",
    "San Jose, Batangas",
    "Lipa City, Batangas",
    "Tanauan City, Batangas",
    "Sto. Tomas City, Batangas",
    "Malvar, Batangas",
    "Ibaan, Batangas",
    "Batangas City, Batangas",
    "Lobo, Batangas",
    "Tingloy, Batangas",
    "San Pascual, Batangas",
    "Bauan, Batangas",
    "Mabini, Batangas",
    "Padre Garcia, Batangas",
    "San Luis, Batangas",
    "Agoncillo, Batangas",
    "San Nicolas, Batangas",
    "Cuenca, Batangas",
    "Taal, Batangas",
    "Santa Teresita, Batangas",
    "Rosario, Batangas",
    "Balete, Batangas",
    "Sto. Tomas, Batangas",
    "Calamba, Laguna",
    "Bay, Laguna",
    "Los Baños, Laguna",
    "Cabuyao, Laguna",
    "Biñan, Laguna",
    "San Pedro, Laguna",
    "Carmona, Cavite",
    "Cavite City, Cavite",
    "Tagaytay City, Cavite",
    "Dasmariñas City, Cavite",
    "Trece Martires City, Cavite",
    "Imus City, Cavite",
    "Bacoor City, Cavite",
    "General Trias City, Cavite",
    "Noveleta, Cavite",
    "Kawit, Cavite",
    "Rosario, Cavite",
    "Tanza, Cavite",
    "Naic, Cavite",
    "Amadeo, Cavite",
    "Gen. Mariano Alvarez, Cavite",
    "Indang, Cavite",
    "Silang, Cavite",
    "Maragondon, Cavite",
    "Ternate, Cavite",
    "Alfonso, Cavite",
    "Magallanes, Cavite",
    "Lemery, Batangas",
    "Calaca, Batangas",
    "Balayan, Batangas",
    "Tuy, Batangas",
    "Nasugbu, Batangas",
    "Calatagan, Batangas",
    "Lian, Batangas",
    "Laurel, Batangas",
    "Talisay, Batangas",
    "San Jose, Batangas",
    "Lipa City, Batangas",
    "Tanauan City, Batangas",
    "Sto. Tomas City, Batangas",
    "Malvar, Batangas",
    "Ibaan, Batangas",
    "Batangas City, Batangas",
    "Lobo, Batangas",
    "Tingloy, Batangas",
    "San Pascual, Batangas",
    "Bauan, Batangas",
    "Mabini, Batangas",
    "Padre Garcia, Batangas",
    "San Luis, Batangas",
    "Agoncillo, Batangas",
    "San Nicolas, Batangas",
    "Cuenca, Batangas",
    "Taal, Batangas",
    "Santa Teresita, Batangas",
    "Rosario, Batangas",
    "Balete, Batangas",
    "Sto. Tomas, Batangas",
    "Lucban, Quezon",
    "Lucena City, Quezon",
    "Sta. Rosa, Laguna",
    "Calamba, Laguna",
    "Los Baños, Laguna",
    "Binangonan, Rizal",
    "Antipolo, Rizal",
    "Angono, Rizal",
    "Taytay, Rizal",
    "Cainta, Rizal",
    "Marikina City, Metro Manila",
    "San Juan City, Metro Manila",
    "Mandaluyong City, Metro Manila",
    "Pasig City, Metro Manila",
    "Quezon City, Metro Manila",
    "Caloocan City, Metro Manila",
    "Valenzuela City, Metro Manila",
    "Malabon City, Metro Manila",
    "Navotas City, Metro Manila",
    "Manila City, Metro Manila",
    "Makati City, Metro Manila",
    "Taguig City, Metro Manila",
    "Pasay City, Metro Manila",
    "Parañaque City, Metro Manila",
    "Las Piñas City, Metro Manila",
    "Muntinlupa City, Metro Manila",
    "Pateros, Metro Manila",
    "San Pedro, Laguna",
    "Biñan, Laguna",
    "Cabuyao, Laguna",
    "San Pablo City, Laguna",
    "Calauan, Laguna",
    "Santa Cruz, Laguna",
    "Victoria, Laguna",
    "Lumban, Laguna",
    "Pila, Laguna",
    "Bay, Laguna",
    "Los Baños, Laguna",
    "Paete, Laguna",
    "Pagsanjan, Laguna",
    "Magdalena, Laguna",
    "Mabitac, Laguna",
    "Siniloan, Laguna",
    "Famy, Laguna",
    "Luisiana, Laguna",
    "Pakil, Laguna",
    "Nagcarlan, Laguna",
    "Rizal, Laguna",
    "Santa Maria, Laguna",
    "Liliw, Laguna",
    "Pila, Laguna",
    "Sta. Cruz, Laguna",
    "Calamba, Laguna",
    "Bay, Laguna",
    "Los Baños, Laguna",
    "Cabuyao, Laguna",
    "Biñan, Laguna",
    "San Pedro, Laguna",
    "Carmona, Cavite",
    "Cavite City, Cavite",
    "Tagaytay City, Cavite",
    "Dasmariñas City, Cavite",
    "Trece Martires City, Cavite",
    "Imus City, Cavite",
    "Bacoor City, Cavite",
    "General Trias City, Cavite",
    "Noveleta, Cavite",
    "Kawit, Cavite",
    "Rosario, Cavite",
    "Tanza, Cavite",
    "Naic, Cavite",
    "Amadeo, Cavite",
    "Gen. Mariano Alvarez, Cavite",
    "Indang, Cavite",
    "Silang, Cavite",
    "Maragondon, Cavite",
    "Ternate, Cavite",
    "Alfonso, Cavite",
    "Magallanes, Cavite",
    "Lemery, Batangas",
    "Calaca, Batangas",
    "Balayan, Batangas",
    "Tuy, Batangas",
    "Nasugbu, Batangas",
    "Calatagan, Batangas",
    "Lian, Batangas",
    "Laurel, Batangas",
    "Talisay, Batangas",
    "San Jose, Batangas",
    "Lipa City, Batangas",
    "Tanauan City, Batangas",
    "Sto. Tomas City, Batangas",
    "Malvar, Batangas",
    "Ibaan, Batangas",
    "Batangas City, Batangas",
    "Lobo, Batangas",
    "Tingloy, Batangas",
    "San Pascual, Batangas",
    "Bauan, Batangas",
    "Mabini, Batangas",
    "Padre Garcia, Batangas",
    "San Luis, Batangas",
    "Agoncillo, Batangas",
    "San Nicolas, Batangas",
    "Cuenca, Batangas",
    "Taal, Batangas",
    "Santa Teresita, Batangas",
    "Rosario, Batangas",
    "Balete, Batangas",
    "Sto. Tomas, Batangas",
    "Lucban, Quezon",
    "Lucena City, Quezon",
    "Sta. Rosa, Laguna",
    "Calamba, Laguna",
    "Los Baños, Laguna",
    "Binangonan, Rizal",
    "Antipolo, Rizal",
    "Angono, Rizal",
    "Taytay, Rizal",
    "Cainta, Rizal",
    "Marikina City, Metro Manila",
    "San Juan City, Metro Manila",
    "Mandaluyong City, Metro Manila",
    "Pasig City, Metro Manila",
    "Quezon City, Metro Manila",
    "Caloocan City, Metro Manila",
    "Valenzuela City, Metro Manila",
    "Malabon City, Metro Manila",
    "Navotas City, Metro Manila",
    "Manila City, Metro Manila",
    "Makati City, Metro Manila",
    "Taguig City, Metro Manila",
    "Pasay City, Metro Manila",
    "Parañaque City, Metro Manila",
    "Las Piñas City, Metro Manila",
    "Muntinlupa City, Metro Manila",
    "Pateros, Metro Manila",
    "San Pedro, Laguna",
    "Biñan, Laguna",
    "Cabuyao, Laguna",
    "San Pablo City, Laguna",
    "Calauan, Laguna",
    "Santa Cruz, Laguna",
    "Victoria, Laguna",
    "Lumban, Laguna",
    "Pila, Laguna",
    "Bay, Laguna",
    "Los Baños, Laguna",
    "Paete, Laguna",
    "Pagsanjan, Laguna",
    "Magdalena, Laguna",
    "Mabitac, Laguna",
    "Siniloan, Laguna",
    "Famy, Laguna",
    "Luisiana, Laguna",
    "Pakil, Laguna",
    "Nagcarlan, Laguna",
    "Rizal, Laguna",
    "Santa Maria, Laguna",
    "Liliw, Laguna",
    "Pila, Laguna",
    "Sta. Cruz, Laguna",
    "Calamba, Laguna",
    "Bay, Laguna",
    "Los Baños, Laguna",
    "Cabuyao, Laguna",
    "Biñan, Laguna",
    "San Pedro, Laguna",
    "Carmona, Cavite",
    "Cavite City, Cavite",
    "Tagaytay City, Cavite",
    "Dasmariñas City, Cavite",
    "Trece Martires City, Cavite",
    "Imus City, Cavite",
    "Bacoor City, Cavite",
    "General Trias City, Cavite",
    "Noveleta, Cavite",
    "Kawit, Cavite",
    "Rosario, Cavite",
    "Tanza, Cavite",
    "Naic, Cavite",
    "Amadeo, Cavite",
    "Gen. Mariano Alvarez, Cavite",
    "Indang, Cavite",
    "Silang, Cavite",
    "Maragondon, Cavite",
    "Ternate, Cavite",
    "Alfonso, Cavite",
    "Magallanes, Cavite",
    "Lemery, Batangas",
    "Calaca, Batangas",
    "Balayan, Batangas",
    "Tuy, Batangas",
    "Nasugbu, Batangas",
    "Calatagan, Batangas",
    "Lian, Batangas",
    "Laurel, Batangas",
    "Talisay, Batangas",
    "San Jose, Batangas",
    "Lipa City, Batangas",
    "Tanauan City, Batangas",
    "Sto. Tomas City, Batangas",
    "Malvar, Batangas",
    "Ibaan, Batangas",
    "Batangas City, Batangas",
    "Lobo, Batangas",
    "Tingloy, Batangas",
    "San Pascual, Batangas",
    "Bauan, Batangas",
    "Mabini, Batangas",
    "Padre Garcia, Batangas",
    "San Luis, Batangas",
    "Agoncillo, Batangas",
    "San Nicolas, Batangas",
    "Cuenca, Batangas",
    "Balete, Batangas",
    "Sto. Tomas, Batangas",
    "Baguio City, Benguet",
    "La Trinidad, Benguet",
    "Itogon, Benguet",
    "Tuba, Benguet",
    "Tublay, Benguet",
    "Bokod, Benguet",
    "Kabayan, Benguet",
    "Atok, Benguet",
    "Kapangan, Benguet",
    "Bauko, Mountain Province",
    "Bontoc, Mountain Province",
    "Sadanga, Mountain Province",
    "Sabangan, Mountain Province",
    "Sagada, Mountain Province",
    "Besao, Mountain Province",
    "Tadian, Mountain Province",
    "Barlig, Mountain Province",
    "Paracelis, Mountain Province",
    "Cauayan City, Isabela",
    "Ilagan City, Isabela",
    "Santiago City, Isabela",
    "Aurora, Isabela",
    "Cabagan, Isabela",
    "Cauayan City, Isabela",
    "Ilagan City, Isabela",
    "Santiago City, Isabela",
    "Aurora, Isabela",
    "Cauayan City, Isabela",
    "Ilagan City, Isabela",
    "Santiago City, Isabela",
    "Aurora, Isabela",
    "Tuguegarao City, Cagayan",
    "Aparri, Cagayan",
    "Lal-lo, Cagayan",
    "Gattaran, Cagayan",
    "Santa Ana, Cagayan",
    "Enrile, Cagayan",
    "Peñablanca, Cagayan",
    "Solana, Cagayan",
    "Rizal, Cagayan",
    "Baggao, Cagayan",
    "Alcala, Cagayan",
    "Iguig, Cagayan",
    "Calayan, Cagayan",
    "Bambang, Nueva Vizcaya",
    "Bayombong, Nueva Vizcaya",
    "Solano, Nueva Vizcaya",
    "Bagabag, Nueva Vizcaya",
    "Diadi, Nueva Vizcaya",
    "Kayapa, Nueva Vizcaya",
    "Quezon, Nueva Vizcaya",
    "Santa Fe, Nueva Vizcaya",
    "Villaverde, Nueva Vizcaya",
    "Dupax del Norte, Nueva Vizcaya",
    "Dupax del Sur, Nueva Vizcaya",
    "Bambang, Nueva Vizcaya",
    "Bayombong, Nueva Vizcaya",
    "Solano, Nueva Vizcaya",
    "Bagabag, Nueva Vizcaya",
    "Diadi, Nueva Vizcaya",
    "Kayapa, Nueva Vizcaya",
    "Quezon, Nueva Vizcaya",
    "Santa Fe, Nueva Vizcaya",
    "Villaverde, Nueva Vizcaya",
    "Dupax del Norte, Nueva Vizcaya",
    "Dupax del Sur, Nueva Vizcaya",
    "Tuguegarao City, Cagayan",
    "Aparri, Cagayan",
    "Lal-lo, Cagayan",
    "Gattaran, Cagayan",
    "Santa Ana, Cagayan",
    "Enrile, Cagayan",
    "Peñablanca, Cagayan",
    "Solana, Cagayan",
    "Rizal, Cagayan",
    "Baggao, Cagayan",
    "Alcala, Cagayan",
    "Iguig, Cagayan",
    "Calayan, Cagayan",
    "Santo Domingo, Nueva Ecija",
    "Cabiao, Nueva Ecija",
    "San Isidro, Nueva Ecija",
    "Aliaga, Nueva Ecija",
    "Licab, Nueva Ecija",
    "Zaragoza, Nueva Ecija",
    "Talavera, Nueva Ecija",
    "Guimba, Nueva Ecija",
    "Quezon, Nueva Ecija",
    "Cabanatuan City, Nueva Ecija",
    "Palayan City, Nueva Ecija",
    "Gapan City, Nueva Ecija",
    "Muñoz City, Nueva Ecija",
    "San Jose City, Nueva Ecija",
    "Talavera, Nueva Ecija",
    "Guimba, Nueva Ecija",
    "Licab, Nueva Ecija",
    "Zaragoza, Nueva Ecija",
    "Aliaga, Nueva Ecija",
    "San Isidro, Nueva Ecija",
    "Cabanatuan City, Nueva Ecija",
    "Palayan City, Nueva Ecija",
    "Gapan City, Nueva Ecija",
    "Muñoz City, Nueva Ecija",
    "San Jose City, Nueva Ecija",
    "Santa Rosa, Nueva Ecija",
    "San Leonardo, Nueva Ecija",
    "Peñaranda, Nueva Ecija",
    "Talugtug, Nueva Ecija",
    "Quezon, Nueva Ecija",
    "Cabanatuan City, Nueva Ecija",
    "Palayan City, Nueva Ecija",
    "Gapan City, Nueva Ecija",
    "Muñoz City, Nueva Ecija",
    "San Jose City, Nueva Ecija",
    "Talavera, Nueva Ecija",
    "Guimba, Nueva Ecija",
    "Licab, Nueva Ecija",
    "Zaragoza, Nueva Ecija",
    "Aliaga, Nueva Ecija",
    "San Isidro, Nueva Ecija",
    "Santa Rosa, Nueva Ecija",
    "San Leonardo, Nueva Ecija",
    "Peñaranda, Nueva Ecija",
    "Talugtug, Nueva Ecija",
    "Santa Rosa, Nueva Ecija",
    "San Leonardo, Nueva Ecija",
    "Peñaranda, Nueva Ecija",
    "Talugtug, Nueva Ecija",
    "Santa Rosa, Nueva Ecija",
    "San Leonardo, Nueva Ecija",
    "Peñaranda, Nueva Ecija",
    "Talugtug, Nueva Ecija",
    "Santa Rosa, Nueva Ecija",
    "San Leonardo, Nueva Ecija",
    "Peñaranda, Nueva Ecija",
    "Talugtug, Nueva Ecija",
    "Santa Rosa, Nueva Ecija",
    "San Leonardo, Nueva Ecija",
    "Peñaranda, Nueva Ecija",
    "Talugtug, Nueva Ecija",
    "Roxas, Isabela",
    "San Manuel, Isabela",
    "Benito Soliven, Isabela",
    "Naguilian, Isabela",
    "Reina Mercedes, Isabela",
    "Alicia, Isabela",
    "Angadanan, Isabela",
    "San Guillermo, Isabela",
    "San Mateo, Isabela",
    "Cauayan City, Isabela",
    "Ilagan City, Isabela",
    "Santiago City, Isabela",
    "Aurora, Isabela",
    "Jones, Isabela",
    "San Agustin, Isabela",
    "San Isidro, Isabela",
    "Echague, Isabela",
    "San Mariano, Isabela",
    "Ramón, Isabela",
    "San Mateo, Isabela",
    "Cordon, Isabela",
    "Luna, Isabela",
    "Cabatuan, Isabela",
    "Maconacon, Isabela",
    "Delfin Albano, Isabela",
    "Tumauini, Isabela",
    "Santa Maria, Isabela",
    "San Pablo, Isabela",
    "Santa Maria, Isabela",
    "San Pablo, Isabela",
    "Tumauini, Isabela",
    "Delfin Albano, Isabela",
    "Maconacon, Isabela",
    "Cabatuan, Isabela",
    "Luna, Isabela",
    "Cordon, Isabela",
    "San Mateo, Isabela",
    "Ramón, Isabela",
    "San Mariano, Isabela",
    "Echague, Isabela",
    "San Isidro, Isabela",
    "San Agustin, Isabela",
    "Jones, Isabela",
    "Aurora, Isabela",
    "Santiago City, Isabela",
    "Ilagan City, Isabela",
    "Cauayan City, Isabela",
    "San Mateo, Isabela",
    "Angadanan, Isabela",
    "Alicia, Isabela",
    "Reina Mercedes, Isabela",
    "Naguilian, Isabela",
    "Benito Soliven, Isabela",
    "San Manuel, Isabela",
    "Roxas, Isabela",
    "Quezon, Nueva Ecija",
    "Cabanatuan City, Nueva Ecija",
    "Palayan City, Nueva Ecija",
    "Gapan City, Nueva Ecija",
    "Muñoz City, Nueva Ecija",
    "San Jose City, Nueva Ecija",
    "Talavera, Nueva Ecija",
    "Guimba, Nueva Ecija",
    "Licab, Nueva Ecija",
    "Zaragoza, Nueva Ecija",
    "Aliaga, Nueva Ecija",
    "San Isidro, Nueva Ecija",
    "Santa Rosa, Nueva Ecija",
    "San Leonardo, Nueva Ecija",
    "Peñaranda, Nueva Ecija",
    "Talugtug, Nueva Ecija",
    "Quezon, Nueva Ecija",
    "Cabanatuan City, Nueva Ecija",
    "Palayan City, Nueva Ecija",
    "Gapan City, Nueva Ecija",
    "Muñoz City, Nueva Ecija",
    "San Jose City, Nueva Ecija",
    "Talavera, Nueva Ecija",
    "Guimba, Nueva Ecija",
    "Licab, Nueva Ecija",
    "Zaragoza, Nueva Ecija",
    "Aliaga, Nueva Ecija",
    "San Isidro, Nueva Ecija",
    "Santa Rosa, Nueva Ecija",
    "San Leonardo, Nueva Ecija",
    "Peñaranda, Nueva Ecija",
    "Talugtug, Nueva Ecija",
    "Tayug, Pangasinan",
    "Umingan, Pangasinan",
    "Balungao, Pangasinan",
    "Binalonan, Pangasinan",
    "San Manuel, Pangasinan",
    "Asingan, Pangasinan",
    "Urdaneta City, Pangasinan",
    "Sison, Pangasinan",
    "Pozorrubio, Pangasinan",
    "Lingayen, Pangasinan",
    "Dagupan City, Pangasinan",
    "San Carlos City, Pangasinan",
    "Alaminos City, Pangasinan",
    "Bayambang, Pangasinan",
    "Basista, Pangasinan",
    "Bautista, Pangasinan",
    "Malasiqui, Pangasinan",
    "Villasis, Pangasinan",
    "Sual, Pangasinan",
    "Pozzorubio, Pangasinan",
    "Mangaldan, Pangasinan",
    "Lingayen, Pangasinan",
    "Urdaneta City, Pangasinan",
    "San Fabian, Pangasinan",
    "Rosales, Pangasinan",
    "Sta. Maria, Pangasinan",
    "Manaoag, Pangasinan",
    "Calasiao, Pangasinan",
    "Binmaley, Pangasinan",
    "San Carlos City, Pangasinan",
    "Dagupan City, Pangasinan",
    "Laoac, Pangasinan",
    "Villasis, Pangasinan",
    "Umingan, Pangasinan",
    "Bayambang, Pangasinan",
    "Urdaneta City, Pangasinan",
    "Lingayen, Pangasinan",
    "San Manuel, Pangasinan",
    "Tayug, Pangasinan",
    "San Quintin, Pangasinan",
    "Asingan, Pangasinan",
    "Sison, Pangasinan",
    "Rosales, Pangasinan",
    "Sta. Maria, Pangasinan",
    "Alaminos City, Pangasinan",
    "Binalonan, Pangasinan",
    "Malasiqui, Pangasinan",
    "Mangatarem, Pangasinan",
    "Aguilar, Pangasinan",
    "Bugallon, Pangasinan",
    "Infanta, Pangasinan",
    "Dasol, Pangasinan",
    "Mabini, Pangasinan",
    "Burgos, Pangasinan",
    "Aguilar, Pangasinan",
    "Bugallon, Pangasinan",
    "Infanta, Pangasinan",
    "Dasol, Pangasinan",
    "Mabini, Pangasinan",
    "Burgos, Pangasinan",
    "Mangatarem, Pangasinan",
    "Bayambang, Pangasinan",
    "Urdaneta City, Pangasinan",
    "Binalonan, Pangasinan",
    "San Manuel, Pangasinan",
    "Tayug, Pangasinan",
    "Sual, Pangasinan",
    "Alcala, Pangasinan",
    "San Jacinto, Pangasinan",
    "Umingan, Pangasinan",
    "Asingan, Pangasinan",
    "Rosales, Pangasinan",
    "Sta. Maria, Pangasinan",
    "Malasiqui, Pangasinan",
    "Bautista, Pangasinan",
    "Bayambang, Pangasinan",
    "San Quintin, Pangasinan",
    "San Carlos City, Pangasinan",
    "Lingayen, Pangasinan",
    "Dagupan City, Pangasinan",
    "San Fabian, Pangasinan",
    "Manaoag, Pangasinan",
    "Mangaldan, Pangasinan",
    "Calasiao, Pangasinan",
    "Binmaley, Pangasinan",
    "Laoac, Pangasinan",
    "Villasis, Pangasinan",
    "Rosales, Pangasinan",
    "Sta. Maria, Pangasinan",
    "Urdaneta City, Pangasinan",
    "San Quintin, Pangasinan",
    "San Carlos City, Pangasinan",
    "Lingayen, Pangasinan",
    "Dagupan City, Pangasinan",
    "San Fabian, Pangasinan",
    "Manaoag, Pangasinan",
    "Mangaldan, Pangasinan",
    "Calasiao, Pangasinan",
    "Binmaley, Pangasinan",
    "Laoac, Pangasinan",
    "Villasis, Pangasinan",
    "Bayambang, Pangasinan",
    "San Manuel, Pangasinan",
    "Tayug, Pangasinan",
    "Sual, Pangasinan",
    "Alcala, Pangasinan",
    "San Jacinto, Pangasinan",
    "Umingan, Pangasinan",
    "Asingan, Pangasinan",
    "Rosales, Pangasinan",
    "Sta. Maria, Pangasinan",
    "Malasiqui, Pangasinan",
    "Bautista, Pangasinan",
    "Urdaneta City, Pangasinan",
    "San Quintin, Pangasinan",
    "San Carlos City, Pangasinan",
    "Lingayen, Pangasinan",
    "Dagupan City, Pangasinan",
    "San Fabian, Pangasinan",
    "Manaoag, Pangasinan",
    "Mangaldan, Pangasinan",
    "Calasiao, Pangasinan",
    "Binmaley, Pangasinan",
    "Laoac, Pangasinan",
    "Villasis, Pangasinan",
    "Rosales, Pangasinan",
    "Sta. Maria, Pangasinan",
    "Mangatarem, Pangasinan",
    "Bani, Pangasinan",
    "Basista, Pangasinan",
    "Bautista, Pangasinan",
    "Bayambang, Pangasinan",
    "Binalonan, Pangasinan",
    "San Manuel, Pangasinan",
    "Santo Tomas, Pangasinan",
    "Sison, Pangasinan",
    "Tayug, Pangasinan",
    "Umingan, Pangasinan",
    "Urdaneta City, Pangasinan",
    "Villasis, Pangasinan",
    "Bautista, Pangasinan",
    "Bayambang, Pangasinan",
    "San Quintin, Pangasinan",
    "Binalonan, Pangasinan",
    "Dagupan City, Pangasinan",
    "San Fabian, Pangasinan",
    "San Jacinto, Pangasinan",
    "San Manuel, Pangasinan",
    "Mangaldan, Pangasinan",
    "Calasiao, Pangasinan",
    "Lingayen, Pangasinan",
    "Binmaley, Pangasinan",
    "Laoac, Pangasinan",
    "Manaoag, Pangasinan",
    "Mangatarem, Pangasinan",
    "Santa Barbara, Pangasinan",
    "Agoo, La Union",
    "Aringay, La Union",
    "Bacnotan, La Union",
    "Bagulin, La Union",
    "Balaoan, La Union",
    "Bangar, La Union",
    "Bauang, La Union",
    "Burgos, La Union",
    "Caba, La Union",
    "Luna, La Union",
    "Naguilian, La Union",
    "Pugo, La Union",
    "Rosario, La Union",
    "San Fernando City, La Union",
    "San Gabriel, La Union",
    "San Juan, La Union",
    "Santo Tomas, La Union",
    "Santol, La Union",
    "Sudipen, La Union",
    "Tubao, La Union",
    "Agoo, La Union",
    "Aringay, La Union",
    "Bacnotan, La Union",
    "Bagulin, La Union",
    "Balaoan, La Union",
    "Bangar, La Union",
    "Bauang, La Union",
    "Burgos, La Union",
    "Caba, La Union",
    "Luna, La Union",
    "Naguilian, La Union",
    "Pugo, La Union",
    "Rosario, La Union",
    "San Fernando City, La Union",
    "San Gabriel, La Union",
    "San Juan, La Union",
    "Santo Tomas, La Union",
    "Santol, La Union",
    "Sudipen, La Union",
    "Tubao, La Union",
    "Aguilar, Pangasinan",
    "Bugallon, Pangasinan",
    "Infanta, Pangasinan",
    "Dasol, Pangasinan",
    "Mabini, Pangasinan",
    "Burgos, Pangasinan",
    "Dagupan City, Pangasinan",
    "Lingayen, Pangasinan",
    "San Carlos City, Pangasinan",
    "Alaminos City, Pangasinan",
    "Bayambang, Pangasinan",
    "Urdaneta City, Pangasinan",
    "San Quintin, Pangasinan",
    "San Manuel, Pangasinan",
    "Tayug, Pangasinan",
    "Sual, Pangasinan",
    "Bautista, Pangasinan",
    "Basista, Pangasinan",
    "Calasiao, Pangasinan",
    "Santa Maria, Pangasinan",
    "Malasiqui, Pangasinan",
    "Mangaldan, Pangasinan",
    "Rosales, Pangasinan",
    "San Jacinto, Pangasinan",
    "Manaoag, Pangasinan",
    "Laoac, Pangasinan",
    "Villasis, Pangasinan",
    "Binmaley, Pangasinan",
    "Sison, Pangasinan",
    "Alcala, Pangasinan",
    "Binalonan, Pangasinan",
    "Umingan, Pangasinan",
    "Asingan, Pangasinan",
    "San Fabian, Pangasinan",
    "Tubao, La Union",
    "Santo Tomas, La Union",
    "Santol, La Union",
    "San Juan, La Union",
    "San Gabriel, La Union",
    "San Fernando City, La Union",
    "Rosario, La Union",
    "Pugo, La Union",
    "Naguilian, La Union",
    "Luna, La Union",
    "Caba, La Union",
    "Burgos, La Union",
    "Bauang, La Union",
    "Bangar, La Union",
    "Bangar, La Union",
    "Balaoan, La Union",
    "Bagulin, La Union",
    "Bacnotan, La Union",
    "Aringay, La Union",
    "Agoo, La Union",
    "Tubao, La Union",
    "Rosario, La Union",
    "San Fernando City, La Union",
    "San Gabriel, La Union",
    "San Juan, La Union",
    "Santo Tomas, La Union",
    "Santol, La Union",
    "Naguilian, La Union",
    "Luna, La Union",
    "Caba, La Union",
    "Burgos, La Union",
    "Bauang, La Union",
    "Bangar, La Union",
    "Balaoan, La Union",
    "Bagulin, La Union",
    "Bacnotan, La Union",
    "Aringay, La Union",
    "Agoo, La Union",
    "Agoo, La Union",
    "Bauang, La Union",
    "Bacnotan, La Union",
    "Bagulin, La Union",
    "Balaoan, La Union",
    "Bangar, La Union",
    "Bauang, La Union",
    "Burgos, La Union",
    "Caba, La Union",
    "Luna, La Union",
    "Naguilian, La Union",
    "Pugo, La Union",
    "Rosario, La Union",
    "San Fernando City, La Union",
    "San Gabriel, La Union",
    "San Juan, La Union",
    "Santo Tomas, La Union",
    "Santol, La Union",
    "Sudipen, La Union",
    "Tubao, La Union",
    "Villasis, Pangasinan",
    "Umingan, Pangasinan",
    "Asingan, Pangasinan",
    "San Fabian, Pangasinan",
    "San Jacinto, Pangasinan",
    "San Manuel, Pangasinan",
    "Sual, Pangasinan",
    "Tayug, Pangasinan",
    "Alcala, Pangasinan",
    "Bautista, Pangasinan",
    "Basista, Pangasinan",
    "Binmaley, Pangasinan",
    "Calasiao, Pangasinan",
    "Lingayen, Pangasinan",
    "Malasiqui, Pangasinan",
    "Mangaldan, Pangasinan",
    "Rosales, Pangasinan",
    "Sison, Pangasinan",
    "San Quintin, Pangasinan",
    "Agoo, La Union",
    "Aringay, La Union",
    "Bacnotan, La Union",
    "Bagulin, La Union",
    "Balaoan, La Union",
    "Bangar, La Union",
    "Bauang, La Union",
    "Burgos, La Union",
    "Caba, La Union",
    "Luna, La Union",
    "Naguilian, La Union",
    "Pugo, La Union",
    "Rosario, La Union",
    "San Fernando City, La Union",
    "San Gabriel, La Union",
    "San Juan, La Union",
    "Santo Tomas, La Union",
    "Santol, La Union",
    "Sudipen, La Union",
    "Tubao, La Union",
    "Agoo, La Union",
    "Aringay, La Union",
    "Bacnotan, La Union",
    "Bagulin, La Union",
    "Balaoan, La Union",
    "Bangar, La Union",
    "Bauang, La Union",
    "Burgos, La Union",
    "Caba, La Union",
    "Luna, La Union",
    "Naguilian, La Union",
    "Pugo, La Union",
    "Rosario, La Union",
    "San Fernando City, La Union",
    "San Gabriel, La Union",
    "San Juan, La Union",
    "Santo Tomas, La Union",
    "Santol, La Union",
    "Sudipen, La Union",
    "Tubao, La Union",
    "Bacnotan, La Union",
    "Bagulin, La Union",
    "Balaoan, La Union",
    "Bangar, La Union",
    "Bauang, La Union",
    "Burgos, La Union",
    "Caba, La Union",
    "Luna, La Union",
    "Naguilian, La Union",
    "Pugo, La Union",
    "Rosario, La Union",
    "San Fernando City, La Union",
    "San Gabriel, La Union",
    "San Juan, La Union",
    "Santo Tomas, La Union",
    "Santol, La Union",
    "Sudipen, La Union",
    "Agoo, La Union",
    "Aringay, La Union",
    "Bacnotan, La Union",
    "Bagulin, La Union",
    "Balaoan, La Union",
    "Bangar, La Union",
    "Bauang, La Union",
    "Burgos, La Union",
    "Caba, La Union",
    "Luna, La Union",
    "Naguilian, La Union",
    "Pugo, La Union",
    "Rosario, La Union",
    "San Fernando City, La Union",
    "San Gabriel, La Union",
    "San Juan, La Union",
    "Santo Tomas, La Union",
    "Santol, La Union",
    "Sudipen, La Union",
    "Tubao, La Union",
    "Tubao, La Union",
    "Tubao, La Union",
    "Sison, Pangasinan",
    "Dagupan City, Pangasinan",
    "Urdaneta City, Pangasinan",
    "San Quintin, Pangasinan",
    "Pozzorubio, Pangasinan",
    "Mangaldan, Pangasinan",
    "Lingayen, Pangasinan",
    "Binmaley, Pangasinan",
    "Santa Barbara, Pangasinan",
    "Bayambang, Pangasinan",
    "Mangatarem, Pangasinan",
    "Umingan, Pangasinan",
    "Basista, Pangasinan",
    "Laoac, Pangasinan",
    "San Nicolas, Pangasinan",
    "Malasiqui, Pangasinan",
    "Alaminos City, Pangasinan",
    "Dagupan City, Pangasinan",
    "San Carlos City, Pangasinan",
    "Bayambang, Pangasinan",
    "Lingayen, Pangasinan",
    "Urdaneta City, Pangasinan",
    "Tayug, Pangasinan",
    "Sual, Pangasinan",
    "Bautista, Pangasinan",
    "San Jacinto, Pangasinan",
    "San Fabian, Pangasinan",
    "Calasiao, Pangasinan",
    "Santa Maria, Pangasinan",
    "Rosales, Pangasinan",
    "Manaoag, Pangasinan",
    "Laoac, Pangasinan",
    "Villasis, Pangasinan",
    "San Quintin, Pangasinan",
    "Umingan, Pangasinan",
    "Asingan, Pangasinan",
    "San Manuel, Pangasinan",
    "Tubao, La Union",
    "Bacnotan, La Union",
    "Bagulin, La Union",
    "Balaoan, La Union",
    "Bangar, La Union",
    "Bauang, La Union",
    "Burgos, La Union",
    "Caba, La Union",
    "Luna, La Union",
    "Naguilian, La Union",
    "Pugo, La Union",
    "Rosario, La Union",
    "San Fernando City, La Union",
    "San Gabriel, La Union",
    "San Juan, La Union",
    "Santo Tomas, La Union",
    "Santol, La Union",
    "Sudipen, La Union",
    "Agoo, La Union",
    "Aringay, La Union",
    "Agoo, La Union",
    "Bauang, La Union",
    "Rosario, La Union",
    "San Fernando City, La Union",
    "San Juan, La Union",
    "Santo Tomas, La Union",
    "Santol, La Union",
    "Sudipen, La Union",
    "Tubao, La Union",
    "Tubao, La Union",
    "Tubao, La Union",
]

complete_address = []
temp_destinations = []
temp_municipality = []
for i in destinations:
    
    sliced = i.split(', ')

    if not i in complete_address:
        complete_address.append(i)
        if not sliced[0] in temp_destinations:
            temp_destinations.append(sliced[0])
        
        if not sliced[1] in temp_municipality:
            temp_municipality.append(sliced[1])
    else:
        print(i)

# print(len(temp_destinations))
print(complete_address)
print('\n')
print(temp_destinations)
# print('\n')
# print(temp_municipality)
raw = input()


# ['Quezon', 'Laguna', 'Rizal', 'Metro Manila', 'Cavite', 'Batangas', 'Benguet', 'Mountain Province', 'Isabela', 'Cagayan', 'Nueva Vizcaya', 'Nueva Ecija', 'Pangasinan', 'La Union']