# Generated by Django 4.2.4 on 2023-08-05 01:40

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BookedPassengers',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('booked_id', models.CharField(max_length=30)),
                ('fare', models.IntegerField(default=0)),
                ('pick_up_location', models.TextField()),
                ('seats_occupied', models.IntegerField(default=0)),
                ('date_recorded', models.DateTimeField(default=datetime.datetime(2023, 8, 5, 9, 40, 29, 470671))),
                ('is_confirmed', models.BooleanField(default=False)),
                ('is_rejected', models.BooleanField(default=False)),
                ('is_cancelled', models.BooleanField(default=False)),
                ('is_dropped', models.BooleanField(default=False)),
                ('date_confirmed', models.DateTimeField(blank=True, default=datetime.datetime(2023, 8, 5, 9, 40, 29, 470671), null=True)),
                ('date_rejected', models.DateTimeField(blank=True, default=datetime.datetime(2023, 8, 5, 9, 40, 29, 470671), null=True)),
                ('date_cancelled', models.DateTimeField(blank=True, default=datetime.datetime(2023, 8, 5, 9, 40, 29, 470671), null=True)),
                ('date_dropped', models.DateTimeField(blank=True, default=datetime.datetime(2023, 8, 5, 9, 40, 29, 470671), null=True)),
                ('destination', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='DriverAccount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('driver_id', models.CharField(max_length=15)),
                ('bday', models.DateField()),
                ('contact_no', models.CharField(max_length=13)),
                ('address', models.TextField()),
                ('is_verified', models.BooleanField(default=False)),
                ('auth_token', models.CharField(max_length=50)),
                ('profile', models.TextField()),
                ('user_id', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='PassengerAccount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('passenger_id', models.CharField(max_length=15)),
                ('bday', models.DateField()),
                ('contact_no', models.CharField(max_length=13)),
                ('address', models.TextField()),
                ('is_verified', models.BooleanField(default=False)),
                ('auth_token', models.CharField(max_length=50)),
                ('profile', models.TextField()),
                ('user_id', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='RentedVan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rent_id', models.CharField(max_length=20)),
                ('package_price', models.IntegerField(default=0)),
                ('from_destination', models.TextField()),
                ('to_destination', models.TextField()),
                ('travel_date', models.DateTimeField()),
                ('date_recorded', models.DateTimeField(default=datetime.datetime(2023, 8, 5, 9, 40, 29, 470671))),
                ('is_confirmed', models.BooleanField(default=False)),
                ('is_rejected', models.BooleanField(default=False)),
                ('is_done', models.BooleanField(default=False)),
                ('driver_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='webpage.driveraccount')),
            ],
        ),
        migrations.CreateModel(
            name='Van',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('plate_no', models.CharField(max_length=20)),
                ('color', models.CharField(max_length=20)),
                ('vehicle_image', models.TextField()),
                ('number_of_seats', models.IntegerField(default=0)),
                ('is_rented', models.BooleanField(default=False)),
                ('is_carpooled', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating', models.IntegerField(default=5)),
                ('comment', models.TextField()),
                ('date_recorded', models.DateTimeField(default=datetime.datetime(2023, 8, 5, 9, 40, 29, 470671))),
                ('review_id', models.CharField(max_length=30)),
                ('carpool_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='webpage.bookedpassengers')),
                ('rent_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='webpage.rentedvan')),
            ],
        ),
        migrations.AddField(
            model_name='rentedvan',
            name='plate_no',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='webpage.van'),
        ),
        migrations.AddField(
            model_name='rentedvan',
            name='rented_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='webpage.passengeraccount'),
        ),
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('notification_id', models.CharField(max_length=20)),
                ('message', models.TextField()),
                ('date_recorded', models.DateTimeField(default=datetime.datetime(2023, 8, 5, 9, 40, 29, 470671))),
                ('is_seen', models.BooleanField(default=False)),
                ('receiver_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='CarpoolVan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('carpool_id', models.CharField(max_length=30)),
                ('available_seat', models.TextField(default=0)),
                ('from_destination', models.TextField()),
                ('to_destination', models.TextField()),
                ('date_recorded', models.DateTimeField(default=datetime.datetime(2023, 8, 5, 9, 40, 29, 470671))),
                ('is_done', models.BooleanField(default=False)),
                ('is_cancelled', models.BooleanField(default=False)),
                ('driver_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='webpage.driveraccount')),
                ('plate_no', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='webpage.van')),
            ],
        ),
        migrations.AddField(
            model_name='bookedpassengers',
            name='carpool_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='webpage.carpoolvan'),
        ),
        migrations.AddField(
            model_name='bookedpassengers',
            name='passenger_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='webpage.passengeraccount'),
        ),
        migrations.CreateModel(
            name='AdminAccount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bday', models.DateField()),
                ('contact_no', models.CharField(max_length=13)),
                ('address', models.TextField()),
                ('auth_token', models.CharField(max_length=50)),
                ('profile', models.TextField()),
                ('user_id', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
