# Generated by Django 4.2.4 on 2023-08-05 01:43

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('webpage', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='carpoolvan',
            name='date_recorded',
            field=models.DateTimeField(default=datetime.datetime(2023, 8, 5, 9, 43, 20, 141415)),
        ),
        migrations.AlterField(
            model_name='notification',
            name='date_recorded',
            field=models.DateTimeField(default=datetime.datetime(2023, 8, 5, 9, 43, 20, 141415)),
        ),
        migrations.AlterField(
            model_name='rentedvan',
            name='date_recorded',
            field=models.DateTimeField(default=datetime.datetime(2023, 8, 5, 9, 43, 20, 141415)),
        ),
        migrations.AlterField(
            model_name='review',
            name='date_recorded',
            field=models.DateTimeField(default=datetime.datetime(2023, 8, 5, 9, 43, 20, 141415)),
        ),
        migrations.CreateModel(
            name='BookedPassenger',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('booked_id', models.CharField(max_length=30)),
                ('fare', models.IntegerField(default=0)),
                ('pick_up_location', models.TextField()),
                ('seats_occupied', models.IntegerField(default=0)),
                ('date_recorded', models.DateTimeField(default=datetime.datetime(2023, 8, 5, 9, 43, 20, 141415))),
                ('is_confirmed', models.BooleanField(default=False)),
                ('is_rejected', models.BooleanField(default=False)),
                ('is_cancelled', models.BooleanField(default=False)),
                ('is_dropped', models.BooleanField(default=False)),
                ('date_confirmed', models.DateTimeField(blank=True, default=datetime.datetime(2023, 8, 5, 9, 43, 20, 141415), null=True)),
                ('date_rejected', models.DateTimeField(blank=True, default=datetime.datetime(2023, 8, 5, 9, 43, 20, 141415), null=True)),
                ('date_cancelled', models.DateTimeField(blank=True, default=datetime.datetime(2023, 8, 5, 9, 43, 20, 141415), null=True)),
                ('date_dropped', models.DateTimeField(blank=True, default=datetime.datetime(2023, 8, 5, 9, 43, 20, 141415), null=True)),
                ('destination', models.TextField()),
                ('carpool_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='webpage.carpoolvan')),
                ('passenger_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='webpage.passengeraccount')),
            ],
        ),
        migrations.AlterField(
            model_name='review',
            name='carpool_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='webpage.bookedpassenger'),
        ),
        migrations.DeleteModel(
            name='BookedPassengers',
        ),
    ]
