# Generated by Django 4.2.4 on 2023-08-14 02:07

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webpage', '0013_alter_bookedpassenger_date_cancelled_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bookedpassenger',
            name='date_recorded',
            field=models.DateTimeField(default=datetime.datetime(2023, 8, 14, 10, 7, 16, 791585)),
        ),
        migrations.AlterField(
            model_name='carpoolvan',
            name='available_seat',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='carpoolvan',
            name='date_recorded',
            field=models.DateTimeField(default=datetime.datetime(2023, 8, 14, 10, 7, 16, 790584)),
        ),
        migrations.AlterField(
            model_name='notification',
            name='date_recorded',
            field=models.DateTimeField(default=datetime.datetime(2023, 8, 14, 10, 7, 16, 787583)),
        ),
        migrations.AlterField(
            model_name='rentedvan',
            name='date_recorded',
            field=models.DateTimeField(default=datetime.datetime(2023, 8, 14, 10, 7, 16, 789584)),
        ),
        migrations.AlterField(
            model_name='review',
            name='date_recorded',
            field=models.DateTimeField(default=datetime.datetime(2023, 8, 14, 10, 7, 16, 792584)),
        ),
    ]
