# Generated by Django 4.2.4 on 2023-09-14 03:27

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webpage', '0031_tourgallery_is_modified_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='tourcommentsection',
            name='is_hearted',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='bookedpassenger',
            name='date_recorded',
            field=models.DateTimeField(default=datetime.datetime(2023, 9, 14, 11, 27, 19, 429426)),
        ),
        migrations.AlterField(
            model_name='carpoolvan',
            name='date_recorded',
            field=models.DateTimeField(default=datetime.datetime(2023, 9, 14, 11, 27, 19, 428427)),
        ),
        migrations.AlterField(
            model_name='messages',
            name='date_seen',
            field=models.DateTimeField(default=datetime.datetime(2023, 9, 14, 11, 27, 19, 430426)),
        ),
        migrations.AlterField(
            model_name='messages',
            name='date_sent',
            field=models.DateTimeField(default=datetime.datetime(2023, 9, 14, 11, 27, 19, 430426)),
        ),
        migrations.AlterField(
            model_name='notification',
            name='date_recorded',
            field=models.DateTimeField(default=datetime.datetime(2023, 9, 14, 11, 27, 19, 427428)),
        ),
        migrations.AlterField(
            model_name='rentedvan',
            name='date_recorded',
            field=models.DateTimeField(default=datetime.datetime(2023, 9, 14, 11, 27, 19, 428427)),
        ),
        migrations.AlterField(
            model_name='review',
            name='date_recorded',
            field=models.DateTimeField(default=datetime.datetime(2023, 9, 14, 11, 27, 19, 430426)),
        ),
        migrations.DeleteModel(
            name='HeartReactions',
        ),
    ]
