# Generated by Django 4.2.4 on 2023-09-14 03:51

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webpage', '0035_heartreactions_is_hearted_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='tourcommentsection',
            name='date_commented',
            field=models.DateTimeField(default=datetime.datetime(2023, 9, 14, 11, 51, 28, 227248)),
        ),
        migrations.AlterField(
            model_name='bookedpassenger',
            name='date_recorded',
            field=models.DateTimeField(default=datetime.datetime(2023, 9, 14, 11, 51, 28, 210292)),
        ),
        migrations.AlterField(
            model_name='carpoolvan',
            name='date_recorded',
            field=models.DateTimeField(default=datetime.datetime(2023, 9, 14, 11, 51, 28, 208293)),
        ),
        migrations.AlterField(
            model_name='messages',
            name='date_seen',
            field=models.DateTimeField(default=datetime.datetime(2023, 9, 14, 11, 51, 28, 214290)),
        ),
        migrations.AlterField(
            model_name='messages',
            name='date_sent',
            field=models.DateTimeField(default=datetime.datetime(2023, 9, 14, 11, 51, 28, 214290)),
        ),
        migrations.AlterField(
            model_name='notification',
            name='date_recorded',
            field=models.DateTimeField(default=datetime.datetime(2023, 9, 14, 11, 51, 28, 200263)),
        ),
        migrations.AlterField(
            model_name='rentedvan',
            name='date_recorded',
            field=models.DateTimeField(default=datetime.datetime(2023, 9, 14, 11, 51, 28, 206260)),
        ),
        migrations.AlterField(
            model_name='review',
            name='date_recorded',
            field=models.DateTimeField(default=datetime.datetime(2023, 9, 14, 11, 51, 28, 213290)),
        ),
    ]
