# Generated by Django 4.2.4 on 2023-12-09 01:47

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webpage', '0037_van_color_coding_alter_bookedpassenger_date_recorded_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='TourCategories',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(max_length=255)),
            ],
        ),
        migrations.AlterField(
            model_name='bookedpassenger',
            name='date_recorded',
            field=models.DateTimeField(default=datetime.datetime(2023, 12, 9, 9, 47, 31, 867112)),
        ),
        migrations.AlterField(
            model_name='carpoolvan',
            name='date_recorded',
            field=models.DateTimeField(default=datetime.datetime(2023, 12, 9, 9, 47, 31, 866112)),
        ),
        migrations.AlterField(
            model_name='messages',
            name='date_seen',
            field=models.DateTimeField(default=datetime.datetime(2023, 12, 9, 9, 47, 31, 868112)),
        ),
        migrations.AlterField(
            model_name='messages',
            name='date_sent',
            field=models.DateTimeField(default=datetime.datetime(2023, 12, 9, 9, 47, 31, 868112)),
        ),
        migrations.AlterField(
            model_name='notification',
            name='date_recorded',
            field=models.DateTimeField(default=datetime.datetime(2023, 12, 9, 9, 47, 31, 864111)),
        ),
        migrations.AlterField(
            model_name='rentedvan',
            name='date_recorded',
            field=models.DateTimeField(default=datetime.datetime(2023, 12, 9, 9, 47, 31, 866112)),
        ),
        migrations.AlterField(
            model_name='review',
            name='date_recorded',
            field=models.DateTimeField(default=datetime.datetime(2023, 12, 9, 9, 47, 31, 868112)),
        ),
        migrations.AlterField(
            model_name='tourcommentsection',
            name='date_commented',
            field=models.DateTimeField(default=datetime.datetime(2023, 12, 9, 9, 47, 31, 873111)),
        ),
    ]
