# Generated by Django 4.2.4 on 2023-12-09 02:46

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('webpage', '0038_tourcategories_alter_bookedpassenger_date_recorded_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='tourgallery',
            name='tour_category',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='webpage.tourcategories'),
        ),
        migrations.AlterField(
            model_name='bookedpassenger',
            name='date_recorded',
            field=models.DateTimeField(default=datetime.datetime(2023, 12, 9, 10, 46, 30, 644229)),
        ),
        migrations.AlterField(
            model_name='carpoolvan',
            name='date_recorded',
            field=models.DateTimeField(default=datetime.datetime(2023, 12, 9, 10, 46, 30, 643230)),
        ),
        migrations.AlterField(
            model_name='messages',
            name='date_seen',
            field=models.DateTimeField(default=datetime.datetime(2023, 12, 9, 10, 46, 30, 645249)),
        ),
        migrations.AlterField(
            model_name='messages',
            name='date_sent',
            field=models.DateTimeField(default=datetime.datetime(2023, 12, 9, 10, 46, 30, 645249)),
        ),
        migrations.AlterField(
            model_name='notification',
            name='date_recorded',
            field=models.DateTimeField(default=datetime.datetime(2023, 12, 9, 10, 46, 30, 639230)),
        ),
        migrations.AlterField(
            model_name='rentedvan',
            name='date_recorded',
            field=models.DateTimeField(default=datetime.datetime(2023, 12, 9, 10, 46, 30, 642230)),
        ),
        migrations.AlterField(
            model_name='review',
            name='date_recorded',
            field=models.DateTimeField(default=datetime.datetime(2023, 12, 9, 10, 46, 30, 644229)),
        ),
        migrations.AlterField(
            model_name='tourcommentsection',
            name='date_commented',
            field=models.DateTimeField(default=datetime.datetime(2023, 12, 9, 10, 46, 30, 648247)),
        ),
    ]
